---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-serverless-alipay-com-v1alpha1-moduledeployment
  failurePolicy: Fail
  name: mmoduledeployment.kb.io
  rules:
  - apiGroups:
    - serverless.alipay.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - moduledeployments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-serverless-alipay-com-v1alpha1-moduledeployment
  failurePolicy: Fail
  name: vmoduledeployment.kb.io
  rules:
  - apiGroups:
    - serverless.alipay.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - moduledeployments
  sideEffects: None
